In [35]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [82]:
df = pd.read_csv("dirty_cafe_sales.csv",encoding="utf8")

In [31]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [ ]:
df.tail()         
df.info()       
df.describe()      
df.columns      
df.shape

In [9]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [10]:
df.isnull().sum().sum()

np.int64(6826)

In [11]:
df.dropna()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9984,TXN_3142496,Smoothie,UNKNOWN,4.0,4.0,Cash,Takeaway,2023-07-27
9986,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9991,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9992,TXN_2739140,Smoothie,4,4.0,16.0,UNKNOWN,In-store,2023-07-05
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [53]:
df.duplicated().sum()

np.int64(0)

In [96]:
missingpercent = df.isnull().mean() * 100
missingpercent.sort_values(ascending=False)

Item                3.33
Price Per Unit      1.79
Total Spent         1.73
Transaction Date    1.59
Quantity            0.00
Transaction ID      0.00
Payment Method      0.00
Location            0.00
dtype: float64

In [ ]:
df["Location"].value_counts()

In [ ]:
df["Location"] = df["Location"].fillna("bfill")

In [99]:
df["Location"].value_counts()

Location
Takeaway    6287
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [91]:
df["Payment Method"] = df["Payment Method"].ffill()

In [ ]:
df["Location"] = df["Location"].fillna(
    df["Location"].median()[0]
)

In [95]:
df["Quantity"] = pd.to_numeric(
    df["Quantity"],
    errors="coerce"
)

df["Quantity"] = df["Quantity"].fillna(
    df["Quantity"].median()
)