In [6]:
import pandas as pd

In [7]:
df= pd.read_csv("random_stock_market_dataset.csv")

In [8]:
df= pd.read_csv("dirty_cafe_sales.csv", na_values=["error","unknown","N/A"])

In [10]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [12]:
df["Transaction Date"].dtype

In [13]:
(df.isnull().mean() * 100)

Transaction ID       0.00
Item                 3.33
Quantity             1.38
Price Per Unit       1.79
Total Spent          1.73
Payment Method      25.79
Location            32.65
Transaction Date     1.59
dtype: float64

In [9]:
df["Date"].value_counts()

Date
1/1/2024      1
1/2/2024      1
1/3/2024      1
1/4/2024      1
1/5/2024      1
1/6/2024      1
1/7/2024      1
1/8/2024      1
1/9/2024      1
1/10/2024     1
1/11/2024     1
1/12/2024     1
1/13/2024     1
1/14/2024     1
1/15/2024     1
1/16/2024     1
1/17/2024     1
1/18/2024     1
1/19/2024     1
1/20/2024     1
1/21/2024     1
1/22/2024     1
1/23/2024     1
1/24/2024     1
1/25/2024     1
1/26/2024     1
1/27/2024     1
1/28/2024     1
1/29/2024     1
1/30/2024     1
1/31/2024     1
2/1/2024      1
2/2/2024      1
2/3/2024      1
2/4/2024      1
2/5/2024      1
2/6/2024      1
2/7/2024      1
2/8/2024      1
2/9/2024      1
2/10/2024     1
2/11/2024     1
2/12/2024     1
2024-02-13    1
2024-02-14    1
2024-02-15    1
2024-02-16    1
2024-02-17    1
2024-02-18    1
2024-02-19    1
2024-02-20    1
2024-02-21    1
2024-02-22    1
2024-02-23    1
2024-02-24    1
2024-02-25    1
2024-02-26    1
2024-02-27    1
2024-02-28    1
2024-02-29    1
Name: count, dtype: int64

In [15]:
df["data_rough"] = df["Date"]

df["Date"] = pd.to_datetime(df["data_rough"], errors="coerce", dayfirst=True)

mask = df["Date"].isna()
df.loc[mask, "Date"] = pd.to_datetime(df.loc[mask, "data_rough"], errors="coerce")

df["Date"] = df["Date"].dt.strftime("%d-%m-%Y")

KeyError: 'Date'

In [11]:
df.head()

         Date    Open    High     Low   Close  Volume  Unnamed: 6 data_rough
0  01-01-2024  296.45  307.31  293.96  303.72   93133         NaN   1/1/2024
1  01-02-2024  190.11  193.10  187.21  191.40   64993         NaN   1/2/2024
2  01-03-2024  197.41  208.64  193.37  205.89   70326         NaN   1/3/2024
3  01-04-2024  253.13  262.67  248.67  258.95   17358         NaN   1/4/2024
4  01-05-2024  241.35  253.09  238.99  252.20   20847         NaN   1/5/2024

In [4]:
months = ["", "January", "February", "March", "April",
    "May", "June", "July", "August",
    "September", "October", "November", "December"]

In [5]:
    df["Month"] = df["data_rough"].dt.month_name()

NameError: name 'df' is not defined

In [12]:
df.to_excel("random_stock_market_dataset.xlsx", index=False)